name: flutter_web_auth_2_platform_interface
description: Platform interface for flutter_web_auth_2 plugin
version: 3.1.0
repository: https://github.com/LinusU/flutter_web_auth_2

environment:
  sdk: ">=2.17.0 <4.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.1.6
